title: "BiteCal"
description: "BiteCal is a platform for logging meals, tracking dietary habits, and gaining insights to make healthier food choices."
url: "https://dlwldms7566.github.io/BiteCal"
author: "BiteCal"
contact_email: "kwen0730@gmail.com"

markdown: kramdown
permalink: pretty
timezone: "Asia/Seoul"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - node_modules
  - .git
  - .vscode

